changelog:
  exclude:
    labels: [ignore-for-release]
  categories:
    - title: Features
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Protocol
      labels: [protocol]
    - title: Documentation
      labels: [documentation]
    - title: Other changes
      labels: ["*"]
